name: Release
on: 
  release:
         types: ['published']

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
      - uses: anchore/sbom-action@v0.3.0
        with:
          image: mwilder26/rkvst-sbom:latest
          format: cyclonedx
          
  publish-sbom:
    name: Publish SBOM to RKVST
    runs-on: ubuntu-latest
    steps:
       - uses: actions/download-artifact@v2
       - uses: mmwilder26/rkvst-sbom@v0.a.3
         env:
           CLIENT_ID: ${{ secrets.CLIENT_ID }}
           CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
         with:
           command: release
           asset_id: assets/650fcc21-4d7c-43c1-a59e-37ce8f0ab1bb
           attachments: '["mwilder26-rkvst-sbom_latest.cyclonedx/mwilder26-rkvst-sbom_latest.cyclonedx"]'
